name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # o la rama que uses

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repo
      - name: Checkout
        uses: actions/checkout@v4

      # Configuración de buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login a DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y publicar la imagen
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mi-app:latest

